replicaCount: 1
applicationName: practical-dapr

image:
  repository: dapracr.azurecr.io/dapr-product-catalog-api
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

service:
  type: ClusterIP
  appPort: 5201
  httpPort: 5202
  grpcPort: 5203

ingress:
  enabled: false

# resources:
#   limits:
#     cpu: "500m"
#   requests:
#     cpu: "100m"

env:
  values:
    - name: DAPR_HTTP_PORT
      value: 5202
    - name: Services__ProductCatalogService__RestUri
      value: http://localhost:5202
    - name: Services__InventoryService__GrpcUri
      value: http://inventory-api:5303
    - name: ConnectionStrings__MainDb
      value: Data Source=sqlserver,1433;Initial Catalog=CoolStoreDb;User Id=sa;Password=P@ssw0rd;MultipleActiveResultSets=True;