{{- $name := include "inventory.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "inventory.fullname" . }}
  labels:
    app: {{ template "inventory.name" . }}
    chart: {{ template "inventory.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "inventory.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "inventory.name" . }}
        release: {{ .Release.Name }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: inventory-api
        dapr.io/port: {{ .Values.service.appPort }}
        dapr.io/config: "tracing"
        dapr.io/log-level: "debug"
    spec:
      {{ if .Values.imagePullSecrets -}}
      imagePullSecrets:
      {{ range .Values.imagePullSecrets -}}
        - name: {{ .name }}
      {{- end -}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: apphttp
              containerPort: {{ .Values.service.appPort }}
              protocol: TCP
            - name: httpPort
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: grpcPort
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
          env:
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end -}}