apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: {{ template "inventory.name" . }}
    chart: {{ template "inventory.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: app-http
      protocol: TCP
      name: app-http
    - port: {{ .Values.service.httpPort }}
      targetPort: http-port
      protocol: TCP
      name: http-port
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc-port
      protocol: TCP
      name: grpc-port
  selector:
    app: {{ template "inventory.name" . }}
    release: {{ .Release.Name }}