replicaCount: 1
applicationName: practical-dapr

image:
  repository: dapracr.azurecr.io/dapr-inventory-api
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

service:
  type: ClusterIP
  appPort: 5301
  httpPort: 5302
  grpcPort: 5303

ingress:
  enabled: false

# resources:
#   limits:
#     cpu: "500m"
#   requests:
#     cpu: "100m"

env:
  values:
    - name: DAPR_HTTP_PORT
      value: 5302
    - name: DAPR_GRPC_PORT
      value: 5303
    - name: ConnectionStrings__MainDb
      value: "Server=sqlserver,1433;Database=CoolStoreDb;User Id=sa;Password=P@ssw0rd;MultipleActiveResultSets=True;"