{{- $name := include "product-catalog.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "product-catalog.fullname" . }}
  labels:
    app: {{ template "product-catalog.name" . }}
    chart: {{ template "product-catalog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "product-catalog.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "product-catalog.name" . }}
        release: {{ .Release.Name }}
      # annotations:
      #   dapr.io/enabled: "true"
      #   dapr.io/id: product-catalog-api
      #   dapr.io/port: "{{ .Values.service.appPort }}"
      #   dapr.io/config: "tracing"
      #   dapr.io/log-level: "debug"
    spec:
      {{ if .Values.imagePullSecrets -}}
      imagePullSecrets:
      {{ range .Values.imagePullSecrets -}}
        - name: {{ .name }}
      {{- end -}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: app-http
              containerPort: {{ .Values.service.appPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
          env:
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end -}}