apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  labels:
    app: {{ template "product-catalog.name" . }}
    chart: {{ template "product-catalog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: app-http
      protocol: TCP
      name: app-http
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "product-catalog.name" . }}
    release: {{ .Release.Name }}
